brewPrice:
  # The percentage of the extendPotions
  extendPotions: 150
  # The percentage of the upgradePotions
  upgradePotions: 170
  # THe price of the Normal Potions
  normalPotions: 2000
smithPrice:
  upgradePrice: 5000

IndianPoker:
  perMoney: 50
gacha:
  1: 100
  2: 100
  3: 100

latitude: 37.69209506374857
longitude: -129.03268279201097
timezone: -9